### ISSUE TITLE
[SPRINT] DP0.2 Time Domain Data exploration

### ISSUE THREAD

**Issue by BrunoSanchez** [LSSTDESC/SprintDayChicago2022#3]
# DP0.2 Time Domain Data exploration

Explore the DP0.2 time domain

Contacts: Bruno S.
Time: Morning
Main communication channel: #desc-dc2-dia
GitHub repo:

## Goals and deliverable
* Share the Data Preview dataset overview
* Make an initial exploration on the recently released DP0.2 dataset
* Create scripts to build light-curves, explore stamps and catalogs
* Probably port some DESC code into the new gen3 and apply it to DP0.2

## Resources and skills needed
Python (matplotlib, pandas, lsst-stack minimum skills). Be an LSST Data Preview delegate to run code yourself.

**Comment by kadrlica** [comment]
Here are some time-domain tutorial notebooks from Rubin CET:
https://github.com/rubin-dp0/tutorial-notebooks/blob/main/07a_DiaObject_Samples.ipynb
https://github.com/rubin-dp0/tutorial-notebooks/blob/main/07b_Variable_Star_Lightcurves.ipynb

**Comment by BrunoSanchez** [comment]
We check the tutorials and explored the dataset!

**Comment by BrunoSanchez** [comment]
Exploration went well, we learned a bunch of interesting things of the RSP (Notebook aspect) for DP0.2.
Produced some light-curves without meaning, but we understand basic schema now. 

Next steps might lead to select SNIa in DP0.2 and get a sample of LCs

**Comment by kadrlica** [comment]
Finding a SNIa has been more difficult than might be expected. You might consider dropping a line to Melissa Graham or Jeff Carlin, or posting something on LSST Community.

**Comment by BrunoSanchez** [comment]
Closing this as the sprint passed more than a year ago.
