### ISSUE TITLE
[SPRINT] Butler integration with seacliff

### ISSUE THREAD

**Issue by arunkannawadi** [LSSTDESC/SprintDayChicago2022#30]
# Butler integration with `seacliff`

Enable `seacliff` to read metadata of `calexp`s via the Butler.

Contacts: @beckermr @arunkannawadi 
Time: 10am-3pm
Main communication channel: #desc-wl-shear
GitHub repo: https://github.com/LSSTDESC/seacliff
In-person/Virtual/Hybrid: In-person primary, but can make it hybrid if anyone remote would like to participate.
Zoom room (if applicable):

## Goals and deliverable

Make `seacliff` read WCS, noise, PSF info etc. from the `calexp` dataset.

## Resources and skills needed

Interest in learning how to interact with the Rubin Butler (middleware)

**Comment by sidneymau** [comment]
In-person: ERC 401
Zoom: DESC 7

**Comment by arunkannawadi** [comment]
Outcome from this sprint: https://github.com/arunkannawadi/exploratory-notebooks/blob/main/DESC%20Hack%20day%20-%20Chicago%202022.ipynb
